spring: 
  datasource:
    url: jdbc:mysql://${CLEARDB_DATABASE_HOST}:3306/${CLEARDB_DATABASE_DB}?reconnect=true
    username: ${CLEARDB_DATABASE_USER}
    password: ${CLEARDB_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      
      use-new-id-generator-mappings: true      

    show-sql: false  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect     
        format_sql: false
        
financeiro:
  jwt:
    expiration: 18000
    secret: ${JWT_SECRET}