spring: 
  datasource:
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/heroku_25442d55948b3dd?reconnect=true
    username: ba23d0688321ea
    password: 037871f0
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      
      use-new-id-generator-mappings: true      

    show-sql: false  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect     
        format_sql: false
        
financeiro:
  jwt:
    expiration: 86400000
    secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$    
