spring: 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/financeiro
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      
      use-new-id-generator-mappings: true      

    show-sql: false  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect     
        format_sql: false