spring: 
  datasource:
    url: jdbc:mysql://{{ lookup('env', 'CLEARDB_DATABASE_HOST') }}:3306/{{ lookup('env', 'CLEARDB_DATABASE_DB') }}?reconnect=true
    username: {{ lookup('env', 'CLEARDB_DATABASE_USER') }}
    password: {{ lookup('env', 'CLEARDB_DATABASE_PASSWORD') }}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      
      use-new-id-generator-mappings: true      

    show-sql: false  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect     
        format_sql: false
        
financeiro:
  jwt:
    expiration: 86400000
    secret: {{ lookup('env', 'JWT_SECRET') }}    
