spring: 
  datasource:
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/heroku_25442d55948b3dd?reconnect=true
    username: ba23d0688321ea
    password: ce4f7ee527086c5
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8

  jpa:
    hibernate:
      ddl-auto: update      
      use-new-id-generator-mappings: true      

    show-sql: false  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect     
        format_sql: false
        
financeiro:
  jwt:
    expiration: 3600000

    secret: asdjflasjdlfjur89818923jasdfoia0909402130sjdlfajsldkfja